format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipSntp}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_NTP_SERVER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: time.google.com}
- type: ElementPosition
  attributes: {x: '603', y: '22', id: tcpipSntp}
